### ISSUE TITLE
Passport not in right files

### ISSUE THREAD

**Issue by jesseDijkman1** [Falicer/Datingapp_Team#12]
Passport configuration files are not included in the actual project (but in 'files' folder). You should add a middleware folder (or file) and put the configuration in that. 

![Screenshot 2020-06-20 at 11 23 01](https://user-images.githubusercontent.com/36187451/85198368-772fce80-b2e8-11ea-8e36-db685415054b.png)

**Comment by Falicer** [comment]
Passport has been moved into the right files and edited to work with the current versions
